version: '3.7'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: couchsync
      MYSQL_ROOT_PASSWORD: password
  web:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      NGINX_PORT: 80
  app:
    build: .
    volumes:
      - ./:/app
    environment:
      NODE_PATH: ./src

volumes:
  db:
