version: '3.7'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: couchsync
      MYSQL_ROOT_PASSWORD: password
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - ./:/app
  web:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
    environment:
      NGINX_PORT: 80

volumes:
  db:
