version: '3.7'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  app:
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:8000
  web:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    volumes:
      - ~/certificates:/etc/nginx/certificates
      - ./nginx/templates:/etc/nginx/templates
      - ../website/out:/www/data
    ports:
      - 443:443
      - 80:80

volumes:
  db:
